# TODO: [ ] - Criar nav
# TODO: [ ] - Criar pag tags/rota
# TODO: [ ] - Criar pag atriz/rota
# TODO: [ ] - Criar pag studio/rota
# TODO: [ ] - Auth
# TODO: [ ] - Pagina User
# TODO: [ ] - JS de onde parou de assistir
# TODO: [ ] - Adicionar recomendações
# TODO: [ ] - Adicionar most populas atriz/ator
# TODO: [ ] - Adicionar favoritos func
# TODO: [ ] - 
# TODO: [ ] - 


git init
git checkout -b 02-03-2024-1
gig add .
git commit -m "Adicionando aside/tags"
git push origin 02-03-2024-1